name: automatic-deployment
on:
  workflow_dispatch:
jobs:
  build-secondary-repo-db:
    runs-on: ubuntu-latest
    steps:
      - name: Post Twitter Status
        uses: julb/action-post-twitter-status@v1
        with:
          message: "Repo updated: New/Updated packages available"
          twitter_app_consumer_api_key: ${{ secrets.TWITTER_APP_CONSUMER_API_KEY }}
          twitter_app_consumer_api_secret_key: ${{ secrets.TWITTER_APP_CONSUMER_API_SECRET_KEY }}
          twitter_app_access_token: ${{ secrets.TWITTER_APP_ACCESS_TOKEN }}
          twitter_app_access_token_secret: ${{ secrets.TWITTER_APP_ACCESS_TOKEN_SECRET }}
    build-listing-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run ls and pipe output sandwiched between Apache HEADER.html and README.html files 
        run: |
          curl https://raw.githubusercontent.com/JovarkOS/jovarkos-repo/main/x86_64/HEADER.html > x86_64/HEADER.html
          curl https://raw.githubusercontent.com/JovarkOS/jovarkos-repo/main/x86_64/README.html > x86_64/README.html
          cat x86_64/HEADER.html | grep -v title > HEADER.html
          echo '<pre style="margin-left: 20px;">' > x86_64/listing
          echo 'Size       Date           Name' > x86_64/listing
          ls -l x86_64 --block-size=M | awk '{ print $5 "       " $6 " " $7 " " $8 "       " $9 }' >> x86_64/listing
          echo '</pre>' >> x86_64/listing
          cat x86_64/HEADER.html x86_64/listing x86_64/README.html > x86_64/listing.html
          rm x86_64/listing
          git config --global user.name 'Lucas Burlingham' 
          git config --global user.email 'lucas@lucasburlingham.me'
          git add x86_64/listing.html
          git commit -m '[ACTIONS] Update file listing'
          git push
