name: automatic-deployment
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: run ls and pipe output sandwiched between Apache HEADER.html and README.html files 
        run: |
          curl https://raw.githubusercontent.com/JovarkOS/jovarkos-repo/main/x86_64/HEADER.html > x86_64/HEADER.html
          curl https://raw.githubusercontent.com/JovarkOS/jovarkos-repo/main/x86_64/README.html > x86_64/README.html
          cat x86_64/HEADER.html | grep -v title > HEADER.html
          echo '<pre style="margin-left: 20px;">' > x86_64/listing
          echo 'Size       Date           Name' > x86_64/listing
          ls -l x86_64 --block-size=M | awk '{ print $5 "       " $6 " " $7 " " $8 "       " $9 }' >> x86_64/listing
          echo '</pre>' >> x86_64/listing
          cat x86_64/HEADER.html x86_64/listing x86_64/README.html > x86_64/listing.html
          rm x86_64/listing
          git config --global user.name 'Lucas Burlingham' 
          git config --global user.email 'lucas@lucasburlingham.me'
          git add x86_64/listing.html
          git commit -m '[ACTIONS] Update file listing'
          git push
  
  build-secondary-repo-db:
    runs-on: ubuntu-latest
      - name: Create identical repo db for backup repo
          run: |
            cp x86_64/jovark-repo.db x86_64/jovark-repo-secondary.db
            git config --global user.name 'Lucas Burlingham'
            git config --global user.email 'lucas@lucasburlingham.me'
            git add x86_64/jovark-repo-secondary.db
            git commit -m '[ACTIONS] Create db file with backup server naming'
            git push